export HOME=/Users/dmonsewicz

. ~/bin/dotfiles/bash/env
. ~/bin/dotfiles/bash/rvm
. ~/bin/dotfiles/bash/nvm

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="ys"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"

# # Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

PATH=$HOME/perl5/bin:$PATH

ORIGINAL_PATH=$PATH

function build_path {
	PATH=$(node bin):$ORIGINAL_PATH
}

PROMPT_COMMAND=build_path

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
